export class UpdateCompanyCommand {
    Id: string;
    FirstName: string;
    LastName: string;
    TypePerson: number;
    CountryRegistryNumber: string;
    StateRegistryNumber: string;
    CityRegistryNumber: string;
    Street: string;
    StreetNumber: string;
    Complement: string;
    NeighborHood: string;
    City: string;
    LogoUrl: string;
    PostalCode: string;
    ZipCode: string;
    State: string;
    Country: string;
    AditionalInfo: string;
    HoursToNotifyOwner: number;
    HoursToNotifyAdmin: number;
    HoursToNotifyMaster: number;
    PhoneNumber1: string;
    PhoneNumber2: string;
    MobilePhoneNumber1: string;
    MobilePhoneNumber2: string;
    EmailAddress: string;
    EmailAdminSystem: string;
}